Traceback (most recent call last):
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 160, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/nbclient/client.py", line 648, in async_setup_kernel
    yield
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
sample_table.write('data/input_sample.ecsv', format='ascii.ecsv')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn [4], line 1[0m
[0;32m----> 1[0m [43msample_table[49m[38;5;241;43m.[39;49m[43mwrite[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mdata/input_sample.ecsv[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;28;43mformat[39;49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mascii.ecsv[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/.pyenv/versions/3.11.0/lib/python3.11/site-packages/astropy/table/connect.py:130[0m, in [0;36mTableWrite.__call__[0;34m(self, serialize_method, *args, **kwargs)[0m
[1;32m    128[0m instance [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_instance
[1;32m    129[0m [38;5;28;01mwith[39;00m serialize_method_as(instance, serialize_method):
[0;32m--> 130[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mregistry[49m[38;5;241;43m.[39;49m[43mwrite[49m[43m([49m[43minstance[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/.pyenv/versions/3.11.0/lib/python3.11/site-packages/astropy/io/registry/core.py:382[0m, in [0;36mUnifiedOutputRegistry.write[0;34m(self, data, format, *args, **kwargs)[0m
[1;32m    377[0m     [38;5;28mformat[39m [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_get_valid_format(
[1;32m    378[0m         [38;5;124m"[39m[38;5;124mwrite[39m[38;5;124m"[39m, data[38;5;241m.[39m[38;5;18m__class__[39m, path, fileobj, args, kwargs
[1;32m    379[0m     )
[1;32m    381[0m writer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_writer([38;5;28mformat[39m, data[38;5;241m.[39m[38;5;18m__class__[39m)
[0;32m--> 382[0m [38;5;28;01mreturn[39;00m [43mwriter[49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/.pyenv/versions/3.11.0/lib/python3.11/site-packages/astropy/io/ascii/connect.py:28[0m, in [0;36mio_write[0;34m(format, table, filename, **kwargs)[0m
[1;32m     26[0m     [38;5;28mformat[39m [38;5;241m=[39m re[38;5;241m.[39msub([38;5;124mr[39m[38;5;124m"[39m[38;5;124m^ascii[39m[38;5;124m\[39m[38;5;124m.[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m"[39m, [38;5;28mformat[39m)
[1;32m     27[0m     kwargs[[38;5;124m"[39m[38;5;124mformat[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28mformat[39m
[0;32m---> 28[0m [38;5;28;01mreturn[39;00m [43mwrite[49m[43m([49m[43mtable[49m[43m,[49m[43m [49m[43mfilename[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/.pyenv/versions/3.11.0/lib/python3.11/site-packages/astropy/io/ascii/ui.py:938[0m, in [0;36mwrite[0;34m(table, output, format, Writer, fast_writer, overwrite, **kwargs)[0m
[1;32m    936[0m     output [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mexpanduser(output)
[1;32m    937[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m overwrite [38;5;129;01mand[39;00m os[38;5;241m.[39mpath[38;5;241m.[39mlexists(output):
[0;32m--> 938[0m         [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m(NOT_OVERWRITING_MSG[38;5;241m.[39mformat(output))
[1;32m    940[0m [38;5;28;01mif[39;00m output [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    941[0m     output [38;5;241m=[39m sys[38;5;241m.[39mstdout

[0;31mOSError[0m: File data/input_sample.ecsv already exists. If you mean to replace it then use the argument "overwrite=True".
OSError: File data/input_sample.ecsv already exists. If you mean to replace it then use the argument "overwrite=True".

